---
- hosts: myhosts
  connection: local
  gather_facts: False
  tasks:
    - name: Validate server authentication input provided by user
      when:
      - (auth_token is not defined)
      ansible.builtin.fail:
        msg: "auth_token is mandatory"

    - name: Check User Privileges when auth_token is defined
      block:
        - register: result
          hpe.ilo.ilo_manage:
            category: Systems
            command: CheckUserPrivileges
            baseuri: "{{ baseuri }}"
            auth_token: "{{ auth_token }}"
            required_permissions: "{{ required_permissions | default(['HostBIOSConfigPriv', 'HostNICConfigPriv', 'HostStorageConfigPriv']) }}"

        - name: User Privileges Status
          debug:
            msg: "{{ result }}"

      when: auth_token is defined
