---
  - name: Define timestamp
    set_fact: timestamp="{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
    run_once: true

  - name: Define file to place results
    ansible.builtin.set_fact:
      template: '{{rootdir}}/{{host}}/{{host}}_{{datatype}}_{{timestamp}}'

  - name: Create dropoff directory for host
    ansible.builtin.file:
      path: "{{ rootdir }}/{{ host }}"
      state: directory

